# Generated by Django 3.0.8 on 2020-07-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200710_1536'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStamp',
        ),
    ]
