# Generated by Django 3.0.8 on 2020-07-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200712_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='start_bid',
            new_name='min_bid',
        ),
    ]
