# Generated by Django 3.0.8 on 2020-07-14 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200714_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=900)),
                ('cmt_date', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_listing', to='auctions.Listing')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['cmt_date'],
            },
        ),
    ]
